/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as QuantumGapRouteImport } from './routes/quantum-gap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumGapRoute = QuantumGapRouteImport.update({
  id: '/quantum-gap',
  path: '/quantum-gap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architecture': typeof ArchitectureRoute
  '/deck': typeof DeckRoute
  '/evidence': typeof EvidenceRoute
  '/identity': typeof IdentityRoute
  '/ledger': typeof LedgerRoute
  '/quantum-gap': typeof QuantumGapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architecture': typeof ArchitectureRoute
  '/deck': typeof DeckRoute
  '/evidence': typeof EvidenceRoute
  '/identity': typeof IdentityRoute
  '/ledger': typeof LedgerRoute
  '/quantum-gap': typeof QuantumGapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/architecture': typeof ArchitectureRoute
  '/deck': typeof DeckRoute
  '/evidence': typeof EvidenceRoute
  '/identity': typeof IdentityRoute
  '/ledger': typeof LedgerRoute
  '/quantum-gap': typeof QuantumGapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/architecture'
    | '/deck'
    | '/evidence'
    | '/identity'
    | '/ledger'
    | '/quantum-gap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/architecture'
    | '/deck'
    | '/evidence'
    | '/identity'
    | '/ledger'
    | '/quantum-gap'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/architecture'
    | '/deck'
    | '/evidence'
    | '/identity'
    | '/ledger'
    | '/quantum-gap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DeckRoute: typeof DeckRoute
  EvidenceRoute: typeof EvidenceRoute
  IdentityRoute: typeof IdentityRoute
  LedgerRoute: typeof LedgerRoute
  QuantumGapRoute: typeof QuantumGapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum-gap': {
      id: '/quantum-gap'
      path: '/quantum-gap'
      fullPath: '/quantum-gap'
      preLoaderRoute: typeof QuantumGapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ArchitectureRoute: ArchitectureRoute,
  DeckRoute: DeckRoute,
  EvidenceRoute: EvidenceRoute,
  IdentityRoute: IdentityRoute,
  LedgerRoute: LedgerRoute,
  QuantumGapRoute: QuantumGapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
